/*
 * Topic:   forwarding-table
 * Seen on:
 *   Junos: ma4_mx204
 *   EVO:   (none)
 * Pair with:
 *  - junos/policy-options/policy-statement/per-packet-load-balance.conf
 * Variables:
 *   $PPLB_NAME   e.g. pplb
 */
routing-options {
    forwarding-table {
        export $PPLB_NAME;
        dynamic-list-next-hop;
        ecmp-fast-reroute;
        chained-composite-next-hop {
            ingress {
                evpn;
                l3vpn;
            }
        }
    }
}
