/*
 * Topic:   IPv6-first transport-class resolution with L3VPN multipath import
 * Seen on:
 *   Junos: mse1_mx304
 *   EVO:   an3_acx7100-48l
 * Pair with:
 *  - junos/policy-options/policy-statement/ps-multipath.conf
 *  - variant:mebs-colour-transport capabilities=transport:colour-classes
 * Variables: none
 */
routing-options {
  resolution {
    rib bgp.l3vpn.0 {
      import PS-MULTIPATH;
    }
    scheme gold-to-bronze-v6 {
      resolution-ribs [ junos-rti-tc-4000.inet6.3 junos-rti-tc-6000.inet6.3 ];
      mapping-community color:0:4000;
    }
    scheme gold-to-bronze {
      resolution-ribs [ junos-rti-tc-4000.inet.3 junos-rti-tc-6000.inet.3 ];
      mapping-community color:0:4000;
    }
  }
}
