/*
 * Topic:   transport-class
 * Seen on:
 *   Junos: mse2_mx304
 *   EVO:   (none)
 * Variant group: mebs-colour-transport
 *   Provides: transport:colour-classes
 * Pair with: none
 * Variables:
 *   $LOOPBACK_ANYCAST_V4   e.g. 1.1.10.10
 *   $TC_EGRESS   e.g. 1.1.0.11
 */
routing-options {
    transport-class {
        auto-create;
        name gold {
            color 4000;
            tunnel-egress {
                end-point $TC_EGRESS;
                end-point $LOOPBACK_ANYCAST_V4;
            }
        }
        name bronze {
            color 6000;
            tunnel-egress {
                end-point $TC_EGRESS;
                end-point $LOOPBACK_ANYCAST_V4;
            }
        }
    }
}
