/*
 * Topic:   transport-class
 * Seen on:
 *   Junos: an4_acx710
 *   EVO:   (none)
 * Variant group: mebs-colour-transport
 *   Provides: transport:colour-classes
 * Pair with: none
 * Variables:
 *   $TC_EGRESS   e.g. 1.1.0.3
 */
routing-options {
    transport-class {
        auto-create;
        fallback {
            none;
        }
        name gold {
            color 4000;
            tunnel-egress {
                end-point $TC_EGRESS;
            }
        }
        name bronze {
            color 6000;
            tunnel-egress {
                end-point $TC_EGRESS;
            }
        }
    }
}
