/*
 * Topic:   Enhanced IP chassis network-services mode
 * Seen on:
 *   Junos: an2_acx5448 an4_acx710
 *   EVO: ag1-1_acx7100-32c ag1-2_acx7100-32c an3_acx7100-48l meg1_acx7100-32c meg2_acx7509
 * Count:
 *   ag1-1_acx7100-32c 1
 *   ag1-2_acx7100-32c 1
 *   an2_acx5448 1
 *   an3_acx7100-48l 1
 *   an4_acx710 1
 *   meg1_acx7100-32c 1
 *   meg2_acx7509 1
 *   total 7
 * Pair with: none
 *
 */
chassis {
  network-services enhanced-ip;
}
