/*
 * Topic:   BGP policy PS-CR-IMPORT (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   cr1_ptx10001-36mr cr2_ptx10001-36mr
 * Count:
 *   cr1_ptx10001-36mr 1
 *   cr2_ptx10001-36mr 1
 *   total 2
 *
 * Highlights:
 *  - As-deployed PS-CR-IMPORT routing policy.
 *
 * Pair with: none
 *
 * Peers with: n/a
 * Variables: none
 */
policy-options {
    policy-statement PS-CR-IMPORT {
        term SET-LP {
            then {
                local-preference 90;
                accept;
            }
        }
    }
}
