/*
 * Topic:   BGP policy PS-IBGP-RR-EXPORT
 * Seen on:
 *   Junos: mdr2_mx10003
 *   EVO:   mdr1_acx7509
 *
 * Highlights:
 *  - As-deployed PS-IBGP-RR-EXPORT routing policy.
 *
 * Pair with:
 *  - evo/policy-options/community/cm-access-fabric.conf
 *  - evo/policy-options/community/cm-metro-fabric.conf
 *  - evo/policy-options/prefix-list/pl-an-region.conf
 *  - evo/policy-options/prefix-list/pl-mse.conf
 *
 * Variables: none
 */
policy-options {
    policy-statement PS-IBGP-RR-EXPORT {
        term MSE-NHS {
            from {
                protocol bgp;
                prefix-list PL-MSE;
            }
            then {
                next-hop self;
                accept;
            }
        }
        term AS63535 {
            from {
                protocol bgp;
                community [ CM-ACCESS-FABRIC CM-METRO-FABRIC ];
            }
            then {
                next-hop self;
                accept;
            }
        }
        term RING {
            from {
                prefix-list PL-AN-REGION;
            }
            then reject;
        }
    }
}
