/*
 * Topic:   Interface: pseudowire subscriber (MEF E-Line / EVPL)
 *
 * Seen on:
 *   Junos: MSE1 (MX304), MSE2 (MX304)
 *
 * Highlights:
 *   - encapsulation flexible-ethernet-services
 *   - ESI multihoming
 *
 * Pair with (same-device dependencies):
 *   - junos/services/evpn-elan-vlan-based-floating-pw.conf
 *   - junos/services/l2circuit-floating-pw.conf
 *
 * Variables:
 *   $PS_ANCHOR     e.g. lt-0/0/0
 *   $PS_SERVICE    e.g. 4004
 *   $PS_TRANSPORT  e.g. ps22
 *   $VESI_ID       e.g. 00:11:11:11:44:11:11:30:02:0a
 *   $VLAN          e.g. 4004
 */
$PS_TRANSPORT {
    anchor-point {
        $PS_ANCHOR;
    }
    vlan-tagging;
    encapsulation flexible-ethernet-services;
    unit 0 {
        encapsulation ethernet-ccc;
    }
    unit $PS_SERVICE {
        encapsulation vlan-bridge;
        vlan-id $VLAN;
        esi {
            $VESI_ID;
            all-active;
        }
    }
}
