/*
 * Topic:
 *   Interface: vlan bridge qinq stacked (MEF E-Access)
 *
 * Seen on:
 *   Junos: MA5 (MX204)
 *
 * Highlights:
 *   - encapsulation vlan-bridge
 *
 * Pair with (same-device dependencies):
 *   - junos/cos/classifiers.conf
 *   - junos/cos/cos-binding-ieee8021p.conf
 *   - junos/cos/cos-binding-mpls.conf
 *   - junos/cos/rewrite-rules.conf
 *   - junos/services/bridge-domain-lsw.conf
 *
 * Variables:
 *   $AC_INTF         e.g. et-0/0/2
 *   $MTU             e.g. 9102
 *   $OUTER_VID_TPID  e.g. 0x88a8.4082
 *   $UNIT            e.g. 4082
 */
$AC_INTF {
    mtu $MTU;
    gigether-options {
        ethernet-switch-profile {
            tag-protocol-id [ 0x8100 0x88A8 ];
        }
    }
    unit $UNIT {
        encapsulation vlan-bridge;
        vlan-tags outer $OUTER_VID_TPID;
    }
}
