/*
 * Topic:   BGP-to-OSPF redistribution policy (for multicast VPN CE routing)
 * Seen on:
 *   Junos: wanedge1_mx304 wanedge2_mx10008
 * Highlights:
 *   - Simple accept-all from protocol bgp; used as OSPF export in NGMVPN VRFs
 *   - Enables BGP-learned VPN routes to be redistributed into VRF-local OSPF
 *   - Also used as iBGP group export on PE devices for multicast signaling
 * Pair with:
 *   - junos/services/ngmvpn-vrf.conf — OSPF export references this policy
 * Variables:
 *   (none — policy is invariant across instances)
 */
policy-options {
    policy-statement bgp-to-ospf {
        from protocol bgp;
        then accept;
    }
}
