/*
 * Topic:   BGP-to-OSPF redistribution policy (for multicast VPN CE routing)
 * Seen on:
 *   Junos: wanedge1 (mx304), wanedge2 (mx10008)
 *   EVO: wanedge3 (acx7509), wanedge4 (acx7100-48l)
 * Highlights:
 *   - Simple accept-all from protocol bgp; used as OSPF export in NGMVPN VRFs
 *   - Enables BGP-learned VPN routes to be redistributed into VRF-local OSPF
 *   - Also used as iBGP group export on PE devices for multicast signaling
 * Pair with (same-device dependencies):
 *   - services/ngmvpn-vrf.conf — OSPF export references this policy
 * Variables:
 *   (none — policy is invariant across instances)
 */
policy-options {
    policy-statement bgp-to-ospf {
        from protocol bgp;
        then accept;
    }
}
