/*
 * Topic:   Prefix-list BORDER-NODES (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   cr2_ptx10001-36mr
 *
 * Highlights:
 *  - As-deployed BORDER-NODES prefix-list.
 *
 * Pair with: none
 *
 * Variables: none
 */
policy-options {
    prefix-list BORDER-NODES {
        1.1.0.8/32;
        1.1.0.9/32;
        1.1.0.10/32;
        1.1.0.11/32;
    }
}
