/*
 * Topic:   Prefix-list PL-AN-REGION (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   mdr1_acx7509
 *
 * Highlights:
 *  - As-deployed PL-AN-REGION prefix-list.
 *
 * Pair with: none
 *
 * Variables: none
 */
policy-options {
    prefix-list PL-AN-REGION {
        1.1.0.12/32;
        1.1.0.13/32;
        1.1.0.14/32;
        1.1.0.15/32;
        1.1.0.16/32;
        1.1.0.17/32;
        1.1.0.18/32;
        1.1.0.19/32;
    }
}
