/*
 * Topic:   Prefix-list PL-FABRIC (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   meg1_acx7100-32c meg2_acx7509
 *
 * Highlights:
 *  - As-deployed PL-FABRIC prefix-list.
 *
 * Pair with: none
 *
 * Variables: none
 */
policy-options {
    prefix-list PL-FABRIC {
        1.1.0.0/32;
        1.1.0.1/32;
        1.1.0.2/32;
        1.1.0.3/32;
        1.1.0.4/32;
        1.1.0.5/32;
        1.1.0.6/32;
        1.1.0.7/32;
    }
}
