/*
 * Topic: EVPN MPLS service with no normalization and export policy
 * Seen on:
 *   Junos: an1_mx204
 *   EVO: (none)
 * Count:
 *   an1_mx204 1
 *   total 1
 * Pair with:
 *  - junos/policy-options/policy-statement/ps-export-l2-color.conf
 *  - variant:mebs-bgp-overlay families=evpn
 *
 * Variables:
 *   $INSTANCE_NAME    e.g. evpn_group_90_700
 *   $AC_INTF          e.g. ae11.700
 *   $LOOPBACK_V4      e.g. 1.1.0.0
 *   $RD_SUB_ASSIGNED  e.g. 7000
 *   $RT_AS            e.g. 63535
 *   $RT_ID            e.g. 7000
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type evpn;
        protocols {
            evpn {
                encapsulation mpls;
                no-control-word;
            }
        }
        vlan-id none;
        no-normalization;
        interface $AC_INTF;
        route-distinguisher $LOOPBACK_V4:$RD_SUB_ASSIGNED;
        vrf-export $INSTANCE_NAME;
        vrf-target target:$RT_AS:$RT_ID;
    }
}