/*
 * Topic:   Prefix-list PL-MSE (Junos)
 * Seen on:
 *   Junos: mdr2_mx10003 mse1_mx304 mse2_mx304
 *   EVO:   (none)
 *
 * Highlights:
 *  - As-deployed PL-MSE prefix-list.
 *
 * Pair with: none
 *
 * Variables: none
 */
policy-options {
    prefix-list PL-MSE {
        1.1.0.10/32;
        1.1.0.11/32;
        1.1.10.10/32;
    }
}
