/*
 * Topic:   BGP policy IMPORT-BGP (Junos)
 * Seen on:
 *   Junos: mse1_mx304
 *   EVO:   (none)
 *
 * Highlights:
 *  - As-deployed IMPORT-BGP routing policy.
 *
 * Pair with:
 *  - junos/policy/loopback-mse1.conf
 *
 * Variables: none
 */
policy-options {
    policy-statement IMPORT-BGP {
        term EVPN {
            from {
                family evpn;
                protocol bgp;
            }
            then accept;
        }
        term LOCAL-REJECT {
            from {
                prefix-list LOOPBACK;
            }
            then reject;
        }
        term ACCEPT {
            then accept;
        }
    }
}
