/*
 * Topic:   RIB group RG-REMOTE-LOOPBACKS (services-edge PEs, Junos)
 * Seen on:
 *   Junos: mse1_mx304 mse2_mx304
 *   EVO:   (none)
 *
 * Highlights:
 *  - As-deployed RG-REMOTE-LOOPBACKS rib-group for the services-edge PEs.
 *
 * Pair with:
 *  - junos/policy/ps-remote-loopbacks-mse.conf
 *
 * Variables: none
 */
routing-options {
    rib-groups {
        RG-REMOTE-LOOPBACKS {
            import-rib [ inet.3 inet.0 inet6.3 ];
            import-policy PS-REMOTE-LOOPBACKS;
        }
    }
}
