/*
 * Topic: VLAN-tagged IPv4 unit
 * Seen on:
 *   Junos: ce2_mx480 wanedge1_mx304 wanedge2_mx10008
 *   EVO: (none)
 * Count:
 *   ce2_mx480 2000
 *   wanedge1_mx304 1718
 *   wanedge2_mx10008 1613
 *   total 5331
 * Pair with: none
 * Peers with: n/a
 * Variables (example values from ce2_mx480):
 *   $IFD         e.g. et-2/0/2
 *   $UNIT        e.g. 1001
 *   $VLAN        e.g. 1001
 *   $AC_ADDR_V4  e.g. 65.65.0.1/24
 */
interfaces {
    $IFD {
        unit $UNIT {
            vlan-id $VLAN;
            family inet {
                address $AC_ADDR_V4;
            }
        }
    }
}
