/*
 * Topic:   NGMVPN (Next-Generation Multicast VPN) — multicast VRF with MVPN, PIM, OSPF CE
 * Seen on:
 *   EVO: wanedge3_acx7509 wanedge4_acx7100-48l
 * Highlights:
 *   - Instance-type vrf with protocols mvpn (draft-rosen NG-MVPN)
 *   - PIM sparse-mode with local RP + process-non-null-as-null-register
 *   - OSPF CE redistribution (bgp-to-ospf export policy)
 *   - provider-tunnel ldp-p2mp with selective per-group tunnels
 *   - 100 multicast VPN instances validated at scale
 * Pair with:
 *   - evo/transport/pim-sparse-rp.conf — global PIM for core multicast
 *   - evo/policy/bgp-to-ospf.conf — redistributes BGP into VRF OSPF
 * JVD service mapping:
 *   100 NGMVPN instances (vpn-mcast_1 through vpn-mcast_100) on 4 WAN Edge PEs
 * Variables:
 *   $VRF_NAME       e.g. vpn-mcast_10
 *   $LOOPBACK_UNIT  e.g. 10
 *   $CE_INTF        e.g. et-1/0/10
 *   $CE_UNIT        e.g. 10
 *   $RP_ADDRESS     e.g. 10.33.33.10
 *   $MCAST_GROUP    e.g. 227.1.1.10/32
 *   $MCAST_SOURCE   e.g. 124.1.10.1/32
 *   $RD             e.g. 10.33.33.10:10
 *   $VRF_TARGET     e.g. 1:10
 */
$VRF_NAME {
    instance-type vrf;
    protocols {
        mvpn;
        ospf {
            area 0.0.0.0 {
                interface lo0.$LOOPBACK_UNIT;
                interface $CE_INTF.$CE_UNIT;
            }
            export bgp-to-ospf;
        }
        pim {
            rp {
                local {
                    address $RP_ADDRESS;
                    group-ranges {
                        $MCAST_GROUP;
                    }
                    process-non-null-as-null-register;
                }
            }
            interface lo0.$LOOPBACK_UNIT {
                mode sparse;
                version 2;
            }
            interface $CE_INTF.$CE_UNIT {
                mode sparse;
                version 2;
            }
        }
    }
    interface $CE_INTF.$CE_UNIT;
    interface lo0.$LOOPBACK_UNIT;
    route-distinguisher $RD;
    vrf-target target:$VRF_TARGET;
    vrf-table-label;
    provider-tunnel {
        ldp-p2mp;
        selective {
            tunnel-limit 1;
            group $MCAST_GROUP {
                source $MCAST_SOURCE {
                    ldp-p2mp;
                }
            }
        }
    }
}
