/*
 * Topic: Described aggregated Ethernet member link through gigether-options
 * Seen on:
 *   Junos: (none)
 *   EVO: p1_ptx10003
 * Count:
 *   p1_ptx10003 2
 *   total 2
 * Pair with: none
 * Peers with: n/a
 * Variables (example values from p1_ptx10003):
 *   $IFD          e.g. et-1/0/6
 *   $DESCRIPTION  e.g. "L2_P1Node to WANEdge1"
 *   $AE_BUNDLE    e.g. ae2
 */
interfaces {
    $IFD {
        description $DESCRIPTION;
        gigether-options {
            802.3ad $AE_BUNDLE;
        }
    }
}
