/*
 * Topic:   VLAN-bridge logical interface with flexible Ethernet services
 * Seen on:
 *   Junos: (none)
 *   EVO: an3_acx7100-48l
 * Count:
 *   an3_acx7100-48l 438
 *   total 438
 *
 * Highlights:
 *  - Flexible VLAN tagging and flexible Ethernet services are configured
 *    on the parent of the VLAN-bridge unit.
 *
 * Pair with:
 *  - variant:mebs-edge-intf-form capabilities=gr:edge-intf
 *
 * Peers with: n/a
 * Variables (example values from mse1_mx304 xe-0/0/3:1):
 *   $UNI_INTF     e.g. xe-0/0/3:1
 *   $UNIT         e.g. 3000
 *   $VLAN         e.g. 3000
 */
interfaces {
    $UNI_INTF {
        apply-groups GR-EDGE-INTF;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        unit $UNIT {
            encapsulation vlan-bridge;
            vlan-id $VLAN;
        }
    }
}
