/*
 * Topic: Core aggregate with unit-level core group
 * Seen on:
 *   Junos: (none)
 *   EVO: ma1-1_acx7024
 * Count:
 *   ma1-1_acx7024 2
 *   total 2
 * Pair with:
 *  - evo/groups/gr-core-intf.conf
 *
 * Variables:
 *   $IFD            e.g. ae88
 *   $CORE_DESC      e.g. "to MA1.1 rtme-acx7024-04 ae88"
 *   $CORE_V4_ADDR   e.g. 10.10.1.118/30
 *   $CORE_V6_ADDR   e.g. 2001::10:10:1:76/126
 */
interfaces {
    $IFD {
        description $CORE_DESC;
        mtu 9192;
        aggregated-ether-options {
            minimum-links 1;
            lacp {
                active;
                periodic fast;
            }
        }
        unit 0 {
            apply-groups GR-CORE-INTF;
            family inet {
                address $CORE_V4_ADDR;
            }
            family iso;
            family inet6 {
                address $CORE_V6_ADDR;
            }
            family mpls;
        }
    }
}