/*
 * Topic:   Flexible Ethernet interface with group application
 * Seen on:
 *   Junos: an4_acx710 ma4_mx204 mse1_mx304 mse2_mx304
 *   EVO: an3_acx7100-48l ma3_acx7100-48l meg1_acx7100-32c
 * Count:
 *   an3_acx7100-48l 2
 *   an4_acx710 1
 *   ma3_acx7100-48l 1
 *   ma4_mx204 1
 *   meg1_acx7100-32c 2
 *   mse1_mx304 3
 *   mse2_mx304 2
 *   total 12
 * Pair with:
 *  - variant:mebs-edge-intf-form capabilities=gr:edge-intf
 *
 * Peers with: n/a
 * Variables:
 *   $IFD   e.g. et-0/0/4
 */
interfaces {
    $IFD {
        apply-groups GR-EDGE-INTF;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
    }
}