/*
 * Topic:   Ethernet CCC physical interface with described family CCC unit zero
 * Seen on:
 *   Junos: (none)
 *   EVO: an3_acx7100-48l
 * Count:
 *   an3_acx7100-48l 1
 *   total 1
 * Pair with: none
 *
 * Peers with: n/a
 * Variables:
 *   $IFD   e.g. et-0/0/7
 */
interfaces {
    $IFD {
        encapsulation ethernet-ccc;
        unit 0 {
            description "to UNI-A1 xe-0/0/6";
            family ccc;
        }
    }
}