/*
 * Topic: Flexible Ethernet edge port at 10G
 * Seen on:
 *   Junos: (none)
 *   EVO: meg2_acx7509
 * Count:
 *   meg2_acx7509 2
 *   total 2
 * Pair with:
 *  - variant:mebs-edge-intf-form capabilities=gr:edge-intf
 *
 * Peers with: n/a
 * Variables:
 *   $IFD   e.g. et-2/0/0
 */
interfaces {
    $IFD {
        apply-groups GR-EDGE-INTF;
        flexible-vlan-tagging;
        speed 10g;
        encapsulation flexible-ethernet-services;
    }
}