/*
 * Topic:   Multihomed edge aggregate member with ether-options
 * Seen on:
 *   Junos: an2_acx5448
 *   EVO: an3_acx7100-48l ma1-1_acx7024 ma1-2_acx7024 meg1_acx7100-32c
 * Count:
 *   an2_acx5448 1
 *   an3_acx7100-48l 1
 *   ma1-1_acx7024 2
 *   ma1-2_acx7024 2
 *   meg1_acx7100-32c 2
 *   total 8
 * Pair with:
 *  - evo/groups/gr-lag-member.conf
 *
 * Peers with: n/a
 * Variables:
 *   $IFD        e.g. et-0/0/6
 *   $AE_BUNDLE  e.g. ae11
 */
interfaces {
    $IFD {
        apply-groups GR-EDGE-INTF-LAG-MEMBER-MH;
        ether-options {
            802.3ad $AE_BUNDLE;
        }
    }
}