/*
 * Topic:   Core interface device
 * Seen on:
 *   Junos: mdr2_mx10003
 *   EVO:   ma3_acx7100-48l
 * Pair with:
 *  - evo/groups/gr-core-intf.conf
 * Variables:
 *   $CORE_DESC   e.g. "to MDR2 rtme-mx-51 ae55"
 *   $IFD   e.g. ae55
 */
interfaces {
    $IFD {
        apply-groups GR-CORE-INTF;
        description $CORE_DESC;
        flexible-vlan-tagging;
        encapsulation flexible-ethernet-services;
        aggregated-ether-options {
            minimum-links 1;
            lacp {
                active;
                periodic fast;
            }
        }
    }
}
