/*
 * Topic:   Core interface device
 * Seen on:
 *   Junos: an2_acx5448 ma4_mx204 mdr2_mx10003
 *   EVO:   ma3_acx7100-48l
 * Pair with:
 *  - evo/groups/gr-core-intf.conf
 * Variables:
 *   $CORE_DESC   e.g. "to AN1 rtme-mx-45 ae73"
 *   $IFD   e.g. ae73
 */
interfaces {
    $IFD {
        apply-groups GR-CORE-INTF;
        description $CORE_DESC;
        aggregated-ether-options {
            minimum-links 1;
            lacp {
                active;
                periodic fast;
            }
        }
    }
}
