/*
 * Topic:   Core interface device
 * Seen on:
 *   Junos: mdr2_mx10003
 *   EVO:   mdr1_acx7509
 * Pair with:
 *  - evo/groups/gr-core-intf.conf
 * Variables:
 *   $CORE_DESC   e.g. "to AG2.2 rtme-mx-51 ae22"
 *   $IFD   e.g. ae22
 */
interfaces {
    $IFD {
        apply-groups GR-CORE-INTF;
        description $CORE_DESC;
        flexible-vlan-tagging;
        mtu 9192;
        encapsulation flexible-ethernet-services;
        aggregated-ether-options {
            minimum-links 1;
            lacp {
                active;
                periodic fast;
            }
        }
    }
}
