/*
 * Topic:   Loopback logical interface
 * Seen on:
 *   Junos: (none)
 *   EVO:   an3_acx7100-48l
 * Pair with: none
 * Variables:
 *   $ISIS_NET   e.g. 49.0000.0010.0100.0002.00
 *   $LOOPBACK_V4_PFX   e.g. 1.1.0.2/32
 *   $LOOPBACK_V6_PFX   e.g. 2001::1:1:0:2/128
 *   $UNIT   e.g. 0
 */
interfaces {
    lo0 {
        unit $UNIT {
            family inet {
                address $LOOPBACK_V4_PFX {
                    primary;
                    preferred;
                }
            }
            family iso {
                address $ISIS_NET;
            }
            family inet6 {
                address $LOOPBACK_V6_PFX {
                    primary;
                }
            }
        }
    }
}
