/*
 * Topic: Described bridge logical interface with all-active ESI
 * Seen on:
 *   Junos: (none)
 *   EVO: an3_acx7100-48l
 * Pair with:
 *  - evo/interfaces/ifd-ae-lacp-fast.conf
 * Variables:
 *   $IFD    e.g. ae11
 *   $UNIT   e.g. 700
 *   $VLAN   e.g. 700
 *   $ESI    e.g. 00:70:11:11:11:11:11:00:00:01
 */
interfaces {
    $IFD {
        unit $UNIT {
            description "evpn service IFL";
            encapsulation vlan-bridge;
            vlan-id $VLAN;
            esi {
                $ESI;
                all-active;
            }
        }
    }
}