/*
 * Topic:   Core logical interface
 * Seen on:
 *   Junos: (none)
 *   EVO:   ma3_acx7100-48l mdr1_acx7509
 * Pair with: none
 * Variables:
 *   $CORE_V4_ADDR   e.g. 10.10.1.137/30
 *   $CORE_V6_ADDR   e.g. 2001::10:10:1:89/126
 *   $IFD   e.g. ae55
 *   $UNIT   e.g. 1
 *   $VLAN   e.g. 1
 */
interfaces {
    $IFD {
        unit $UNIT {
            vlan-id $VLAN;
            family inet {
                address $CORE_V4_ADDR;
            }
            family iso;
            family inet6 {
                address $CORE_V6_ADDR;
            }
            family mpls;
        }
    }
}
