/*
 * Topic:   Core logical interface
 * Seen on:
 *   Junos: ma5_mx204
 *   EVO:   ma3_acx7100-48l
 * Pair with:
 *  - evo/groups/gr-core-intf.conf
 * Variables:
 *   $CORE_V4_ADDR   e.g. 10.10.2.153/30
 *   $CORE_V6_ADDR   e.g. 2001::10:10:2:99/126
 *   $IFD   e.g. et-0/0/51
 *   $UNIT   e.g. 1
 *   $VLAN   e.g. 1
 */
interfaces {
    $IFD {
        unit $UNIT {
            apply-groups GR-CORE-INTF;
            vlan-id $VLAN;
            family inet {
                address $CORE_V4_ADDR;
            }
            family iso;
            family inet6 {
                address $CORE_V6_ADDR;
            }
            family mpls;
        }
    }
}
