/*
 * Topic:   IS-IS SR-MPLS process settings
 * Seen on:
 *   Junos: an1_mx204 an2_acx5448 an4_acx710
 *   EVO:   (none)
 * Variables:
 *   $NODE_SID_V4   e.g. 0
 *   $NODE_SID_V6   e.g. 100
 */
protocols {
  isis {
    apply-groups GR-ISIS-BCP;
    source-packet-routing {
      node-segment {
        ipv4-index $NODE_SID_V4;
        ipv6-index $NODE_SID_V6;
      }
      flex-algorithm [ 128 129 ];
      strict-asla-based-flex-algorithm;
      explicit-null;
      traffic-statistics {
        statistics-granularity per-interface;
      }
    }
    level 1 {
      purge-originator empty;
      wide-metrics-only;
    }
    level 2 disable;
    spf-options {
      microloop-avoidance {
        post-convergence-path {
          delay 5000;
        }
      }
    }
    backup-spf-options {
      use-post-convergence-lfa maximum-labels 3;
      use-source-packet-routing;
    }
    traffic-engineering {
      advertisement {
        application-specific {
          all-applications;
        }
      }
    }
    export PS-ISIS-EXPORT;
  }
}
