/*
 * Topic:   MPLS segment routing
 * Seen on:
 *   Junos: mse1_mx304
 *   EVO:   (none)
 * Count:
 *   mse1_mx304 1
 *   total 1
 * Variant group: mebs-mpls-admin-groups
 *   Provides: transport:mpls-admin-groups
 * Pair with:
 *  - junos/interfaces/ifl-loopback-primary-iso-sr-v6.conf
 * Peers with: n/a
 * Variables: none
 */
protocols {
    mpls {
        admin-groups {
            blue 1;
            green 2;
            red 3;
        }
        no-propagate-ttl;
        icmp-tunneling;
        label-range {
            srgb-label-range 16000 24000;
        }
        ipv6-tunneling;
        interface lo0.0;
    }
}
