/*
 * Topic:   BGP community CM-L3VPN-PUB
 * Seen on:
 *   Junos: an1_mx204 an2_acx5448 an4_acx710 ma2_mx204 ma4_mx204 ma5_mx204 mdr2_mx10003 mse1_mx304 mse2_mx304
 *   EVO:   ag1-1_acx7100-32c ag1-2_acx7100-32c an3_acx7100-48l cr1_ptx10001-36mr cr2_ptx10001-36mr ma1-1_acx7024 ma1-2_acx7024 ma3_acx7100-48l mdr1_acx7509 meg1_acx7100-32c meg2_acx7509
 *
 * Highlights:
 *  - Route target tagging the public L3VPN prefixes an export policy
 *    chooses to advertise beyond the customer VRF.
 *
 * Pair with: none
 *
 * Variables:
 *   $RING_COMMUNITY_AS      e.g. 63536
 */
policy-options {
    community CM-L3VPN-PUB members target:$RING_COMMUNITY_AS:22222;
}
