/*
 * Topic:   Transport-class colour community gold
 * Seen on:
 *   Junos: an1_mx204 an2_acx5448 an4_acx710 ma4_mx204 ma5_mx204 mse1_mx304 mse2_mx304
 *   EVO:   an3_acx7100-48l ma1-1_acx7024 ma1-2_acx7024 ma3_acx7100-48l meg1_acx7100-32c meg2_acx7509
 *
 * Highlights:
 *  - Transport Class color community for the gold class (`color:0:4000`).
 *
 * Pair with: none
 *
 * Variables:
 *   $COLOR_COMMUNITY   e.g. map2gold
 */
policy-options {
    community $COLOR_COMMUNITY members color:0:4000;
}
