/*
 * Topic:   Loopback logical interface
 * Seen on:
 *   Junos: mse1_mx304
 *   EVO:   (none)
 * Pair with: none
 * Variables:
 *   $ISIS_NET   e.g. 49.0005.0010.0100.0010.00
 *   $LOOPBACK_SR_V6   e.g. 2001::1:1:10:a
 *   $LOOPBACK_V4_PFX   e.g. 1.1.0.10/32
 *   $LOOPBACK_V6_PFX   e.g. 2001::1:1:0:a/128
 *   $UNIT   e.g. 0
 */
interfaces {
    lo0 {
        unit $UNIT {
            family inet {
                address $LOOPBACK_V4_PFX {
                    primary;
                }
            }
            family iso {
                address $ISIS_NET;
            }
            family inet6 {
                address $LOOPBACK_V6_PFX {
                    primary;
                }
                address $LOOPBACK_SR_V6/128;
            }
        }
    }
}
