/*
 * Topic: RADIUS VRF attaching the RADIUS server with OSPF
 * Seen on:
 *   Junos: (none)
 *   EVO: cr1_ptx10004
 * Count:
 *   cr1_ptx10004 1
 *   total 1
 * Highlights:
 *  - Runs OSPF area 0 toward the RADIUS server segment and redistributes BGP-learned routes into it through `PS-REDIS-OSPF`.
 *  - Imports and exports routes through `PS-RADIUS-VRF-IMPORT` and `PS-RADIUS-VRF-EXPORT`, with an additional `vrf-target`.
 * Pair with:
 *  - evo/interfaces/ifl-loopback-primary.conf
 *  - evo/policy-options/policy-statement/ps-radius-vrf-export.conf
 *  - evo/policy-options/policy-statement/ps-radius-vrf-import-subscribers.conf
 *  - evo/policy-options/policy-statement/ps-redis-ospf.conf
 *
 * Variables (example values from cr1_ptx10004):
 *   $AC_IFL           e.g. et-0/0/20:0.0
 *   $UNIT             e.g. 11
 *   $RD_SUB_ADMIN     e.g. 111.111.111.111
 *   $RD_SUB_ASSIGNED  e.g. 1111
 *   $RT_AS            e.g. 11111
 *   $RT_ID            e.g. 111
 */
routing-instances {
    RADIUS {
        instance-type vrf;
        protocols {
            ospf {
                area 0.0.0.0 {
                    interface $AC_IFL;
                }
                export PS-REDIS-OSPF;
            }
        }
        interface $AC_IFL;
        interface lo0.$UNIT;
        route-distinguisher $RD_SUB_ADMIN:$RD_SUB_ASSIGNED;
        vrf-import PS-RADIUS-VRF-IMPORT;
        vrf-export PS-RADIUS-VRF-EXPORT;
        vrf-target target:$RT_AS:$RT_ID;
        vrf-table-label;
    }
}
