/*
 * Topic:   Routing policy statements for BGP/OSPF/direct protocol redistribution
 * Seen on:
 *   Junos: wanedge1_mx304 wanedge2_mx10004 ap1_mx304 ap2_mx10004
 *   EVO:   p1_ptx10003-80c p2_ptx10001-36mr
 *
 * Highlights:
 *  - PS-ADV_DIRECT: redistributes directly-connected routes into BGP
 *  - PS-BGP-TO-OSPF: leaks BGP-learned routes into OSPF (for CE reachability)
 *  - PS-send-ospf: exports OSPF routes into BGP for VPN distribution
 *  - Simple accept-all policies — no route-filtering or manipulation
 *
 * Pair with:
 *  - evo/transport/ibgp-core-mesh.conf  (export policies referenced in BGP group)
 *
 * Variables (example values from p1_ptx10003-80c):
 *   $DIRECT_POLICY_NAME   e.g. PS-ADV_DIRECT
 *   $BGP_TO_OSPF_NAME     e.g. PS-BGP-TO-OSPF
 *   $OSPF_TO_BGP_NAME     e.g. PS-send-ospf
 */

policy-options {
    policy-statement $DIRECT_POLICY_NAME {
        from protocol direct;
        then accept;
    }
    policy-statement $BGP_TO_OSPF_NAME {
        from protocol bgp;
        then accept;
    }
    policy-statement $OSPF_TO_BGP_NAME {
        from protocol ospf;
        then accept;
    }
}
