/*
 * Topic: Hash key on the top three MPLS labels
 * Seen on:
 *   Junos: (none)
 *   EVO: p1_ptx10003
 * Count:
 *   p1_ptx10003 1
 *   total 1
 * Pair with: none
 * Peers with: n/a
 * Variables: none
 */
forwarding-options {
    hash-key {
        family mpls {
            label-1;
            label-2;
            label-3;
        }
    }
}
