/*
 * Topic: Bridge domain with two units
 * Seen on:
 *   Junos: ce2_mx480
 *   EVO: (none)
 * Count:
 *   ce2_mx480 94
 *   total 94
 * Pair with:
 *  - junos/interfaces/ifl-vlan-bridge.conf
 *
 * Peers with: n/a
 * Variables (example values from ce2_mx480):
 *   $BD_NAME   e.g. BD4001
 *   $AC_IFL_A  e.g. et-2/0/2.4001
 *   $AC_IFL_B  e.g. xe-2/0/0:1.4001
 */
bridge-domains {
    $BD_NAME {
        interface $AC_IFL_A;
        interface $AC_IFL_B;
    }
}
