/*
 * Topic: VRF export policy PS-RADIUS-VRF-EXPORT
 * Seen on:
 *   Junos: (none)
 *   EVO: cr1_ptx10004
 * Count:
 *   cr1_ptx10004 1
 *   total 1
 * Highlights:
 *  - Tags direct routes with `PS-RADIUS-COMM` and next-hop self.
 * Pair with:
 *  - evo/policy-options/community/cm-ps-radius-comm.conf
 *
 * Peers with: n/a
 * Variables: none
 */
policy-options {
    policy-statement PS-RADIUS-VRF-EXPORT {
        term 1 {
            from protocol direct;
            then {
                community add PS-RADIUS-COMM;
                next-hop self;
                accept;
            }
        }
    }
}
