/*
 * Topic: NG-MVPN VRF with a static PIM RP, a local group range and null-register processing over LDP point-to-multipoint tunnels
 * Seen on:
 *   Junos: (none)
 *   EVO: wanedge4_acx7100-48l
 * Count:
 *   wanedge4_acx7100-48l 99
 *   total 99
 * Highlights:
 *   - NG-MVPN VRF: `mvpn` signals multicast state over BGP, and `ldp-p2mp` provider tunnels carry it, with one selective tunnel for the configured source and group.
 *   - OSPF inside the VRF advertises the access subnet and VRF loopback toward the site; `bgp-to-ospf` redistributes remote VPN routes.
 * Pair with: none
 * Variables (example values from wanedge4_acx7100-48l):
 *   $INSTANCE_NAME        e.g. vpn-mcast_10
 *   $UNIT                 e.g. 10
 *   $AC_IFL               e.g. et-0/0/1.10
 *   $MCAST_GROUP_V4_PFX   e.g. 227.1.1.10/32
 *   $PIM_RP_V4            e.g. 10.33.33.10
 *   $LOOPBACK_VRF_V4      e.g. 10.44.44.10
 *   $RD_SUB_ASSIGNED      e.g. 10
 *   $RT_AS                e.g. 1
 *   $RT_ID                e.g. 10
 *   $MCAST_SOURCE_V4_PFX  e.g. 124.1.10.1/32
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type vrf;
        protocols {
            mvpn;
            ospf {
                area 0.0.0.0 {
                    interface lo0.$UNIT;
                    interface $AC_IFL;
                }
                export bgp-to-ospf;
            }
            pim {
                rp {
                    local {
                        group-ranges {
                            $MCAST_GROUP_V4_PFX;
                        }
                        process-non-null-as-null-register;
                    }
                    static {
                        address $PIM_RP_V4;
                    }
                }
                interface lo0.$UNIT {
                    mode sparse;
                    version 2;
                }
                interface $AC_IFL {
                    mode sparse;
                    version 2;
                }
            }
        }
        interface $AC_IFL;
        interface lo0.$UNIT;
        route-distinguisher $LOOPBACK_VRF_V4:$RD_SUB_ASSIGNED;
        vrf-target target:$RT_AS:$RT_ID;
        vrf-table-label;
        provider-tunnel {
            ldp-p2mp;
            selective {
                tunnel-limit 1;
                group $MCAST_GROUP_V4_PFX {
                    source $MCAST_SOURCE_V4_PFX {
                        ldp-p2mp;
                    }
                }
            }
        }
    }
}
