/*
 * Topic: NG-MVPN VRF vpn-mcast_1 with a VRF iBGP session acting as PIM RP
 * Seen on:
 *   Junos: (none)
 *   EVO: wanedge3_acx7509
 * Count:
 *   wanedge3_acx7509 1
 *   total 1
 * Highlights:
 *   - NG-MVPN VRF: `mvpn` signals multicast state over BGP, and `ldp-p2mp` provider tunnels carry it, with one selective tunnel for the configured source and group.
 *   - OSPF inside the VRF advertises the access subnet and VRF loopback toward the site; `bgp-to-ospf` redistributes remote VPN routes.
 * Pair with: none
 * Variables: none
 */
routing-instances {
    vpn-mcast_1 {
        instance-type vrf;
        protocols {
            bgp {
                group mcast_1 {
                    type internal;
                    peer-as 64512;
                    neighbor 10.11.11.1;
                }
            }
            mvpn;
            ospf {
                area 0.0.0.0 {
                    interface lo0.1;
                    interface et-1/0/10.1;
                }
                export bgp-to-ospf;
            }
            pim {
                rp {
                    local {
                        address 10.33.33.1;
                        group-ranges {
                            227.1.1.1/32;
                        }
                        process-non-null-as-null-register;
                    }
                }
                interface lo0.1;
                interface et-1/0/10.1 {
                    mode sparse;
                }
            }
        }
        interface et-1/0/10.1;
        interface lo0.1;
        route-distinguisher 10.33.33.1:1;
        vrf-target target:1:1;
        vrf-table-label;
        provider-tunnel {
            ldp-p2mp;
            selective {
                tunnel-limit 1;
                group 227.1.1.1/32 {
                    source 124.1.1.1/32 {
                        ldp-p2mp;
                    }
                }
            }
        }
    }
}
