/*
 * Topic:   iBGP Route Reflector — inet-vpn, l2vpn families with cluster-id
 * Seen on:
 *   EVO: p1_ptx10003 p2_ptx10001-36mr
 * Highlights:
 *   - Route Reflector with cluster-id (cluster = RR loopback)
 *   - inet-vpn + l2vpn signaling + inet unicast (for labeled routes)
 *   - Reflects to all PE clients (wanedge1-4)
 *   - BFD liveness detection + graceful-restart + multipath
 *   - send-ospf export policy redistributes OSPF into BGP for VPN reachability
 * Pair with:
 *   - evo/transport/ospf-lfa.conf — IGP reachability to PE loopbacks
 *   - evo/transport/ldp.conf — label distribution
 * Variables:
 *   $LOCAL_ADDRESS  e.g. 1.1.1.8
 *   $CLUSTER_ID     e.g. 1.1.1.8
 *   $LOCAL_AS       e.g. 64512
 *   $PE_NEIGHBOR_1  e.g. 2.2.2.2
 *   $PE_NEIGHBOR_2  e.g. 4.4.4.4
 *   $PE_NEIGHBOR_3  e.g. 5.5.5.5
 *   $PE_NEIGHBOR_4  e.g. 7.7.7.7
 */
protocols {
    bgp {
        group ibgp {
            type internal;
            local-address $LOCAL_ADDRESS;
            family inet {
                any;
            }
            family inet-vpn {
                any;
            }
            family l2vpn {
                signaling;
            }
            export send-ospf;
            cluster $CLUSTER_ID;
            local-as $LOCAL_AS;
            graceful-restart;
            multipath;
            bfd-liveness-detection {
                minimum-interval 10;
                multiplier 3;
            }
            neighbor $PE_NEIGHBOR_1;
            neighbor $PE_NEIGHBOR_2;
            neighbor $PE_NEIGHBOR_3;
            neighbor $PE_NEIGHBOR_4;
        }
        advertise-peer-as;
    }
}
