/*
 * Topic: Loopback logical interface
 * Seen on:
 *   Junos: (none)
 *   EVO: agn1_acx7100-32c agn2_acx7100-32c an1_acx7024 an2_acx7100-48l an3_acx7100-48l an4_acx7100-48l an5_acx7100-48l cr1_ptx10004
 * Count:
 *   agn1_acx7100-32c 1
 *   agn2_acx7100-32c 1
 *   an1_acx7024 1
 *   an2_acx7100-48l 1
 *   an3_acx7100-48l 1
 *   an4_acx7100-48l 1
 *   an5_acx7100-48l 1
 *   cr1_ptx10004 1
 *   total 8
 * Highlights:
 *  - Primary IPv4 and IPv6 loopback addresses plus the IS-IS NET.
 * Pair with: none
 *
 * Peers with: n/a
 * Variables (example values from agn1_acx7100-32c):
 *   $UNIT             e.g. 0
 *   $LOOPBACK_V4_PFX  e.g. 192.168.0.5/32
 *   $ISIS_NET         e.g. 49.0000.0010.0100.0005.00
 *   $LOOPBACK_V6_PFX  e.g. 2001:db8::192:168:0:5/128
 */
interfaces {
    lo0 {
        unit $UNIT {
            family inet {
                address $LOOPBACK_V4_PFX {
                    primary;
                }
            }
            family iso {
                address $ISIS_NET;
            }
            family inet6 {
                address $LOOPBACK_V6_PFX {
                    primary;
                }
            }
        }
    }
}
