/*
 * Topic: Policy-options group application
 * Seen on:
 *   Junos: (none)
 *   EVO: an3_acx7100-48l
 * Count:
 *   an3_acx7100-48l 1
 *   total 1
 * Pair with: none
 *
 * Variables:
 *   $GROUP_A   e.g. GR-L3VPN-OSPF-COLOR-MAP
 */
policy-options {
    apply-groups $GROUP_A;
}