/*
 * Topic:   Prefix-list PL-MSE (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   mdr1_acx7509
 *
 * Highlights:
 *  - As-deployed PL-MSE prefix-list.
 *
 * Pair with: none
 *
 * Variables: none
 */
policy-options {
    prefix-list PL-MSE {
        1.1.0.10/32;
        1.1.0.11/32;
        1.1.10.10/32;
    }
}
