/*
 * Topic:   BGP policy PS-BGP-TRANSPORT-EXPORT (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   ma1-1_acx7024 ma1-2_acx7024 ma3_acx7100-48l
 *
 * Highlights:
 *  - As-deployed PS-BGP-TRANSPORT-EXPORT routing policy.
 *
 * Pair with:
 *  - evo/policy/communities.conf
 *
 * Variables: none
 */
policy-options {
    policy-statement PS-BGP-TRANSPORT-EXPORT {
        term ORIGIN {
            then {
                community add CM-METRO-RING;
                next term;
            }
        }
        term LOOPBACK {
            from protocol [ direct bgp ];
            then {
                next-hop self;
                accept;
            }
        }
        term LU {
            from rib inet.3;
            then reject;
        }
        term CT {
            from rib bgp.transport.3;
            then reject;
        }
        term ACCEPT-NHS {
            then {
                next-hop self;
                accept;
            }
        }
    }
}
