/*
 * Topic:   BGP policy PS-BGP-EXPORT-RING (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   cr2_ptx10001-36mr
 *
 * Highlights:
 *  - As-deployed PS-BGP-EXPORT-RING routing policy.
 *
 * Pair with:
 *  - evo/policy/border-nodes.conf
 *  - evo/policy/communities.conf
 *  - evo/policy/pl-metro-ring.conf
 *
 * Variables: none
 */
policy-options {
    policy-statement PS-BGP-EXPORT-RING {
        term LOOP_PREVENT {
            from community [ CM-ACCESS-FABRIC CM-REGIONAL-BORDER ];
            then reject;
        }
        term FROM-MSE {
            from {
                community CM-SERVICE-EDGE;
                prefix-list PL-METRO-RING;
            }
            then {
                next-hop self;
                accept;
            }
        }
        term BORDER-LOOPBACKS {
            from {
                prefix-list BORDER-NODES;
            }
            then {
                community add CM-REGIONAL-BORDER;
                accept;
            }
        }
        term REJECT {
            then reject;
        }
    }
}
