/*
 * Topic:   BGP policy PS-BGP-RR-EXPORT (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   meg1_acx7100-32c meg2_acx7509
 *
 * Highlights:
 *  - As-deployed PS-BGP-RR-EXPORT routing policy.
 *
 * Pair with:
 *  - evo/policy/communities.conf
 *  - evo/policy/pl-core.conf
 *  - evo/policy/pl-fabric.conf
 *
 * Variables: none
 */
policy-options {
    policy-statement PS-BGP-RR-EXPORT {
        term CORE-NHS {
            from {
                protocol bgp;
                prefix-list PL-CORE;
            }
            then {
                next-hop self;
                accept;
            }
        }
        term AS63536 {
            from {
                protocol bgp;
                community [ CM-METRO-RING CM-REGIONAL-BORDER CM-SERVICE-EDGE ];
            }
            then accept;
        }
        term FABRIC {
            from {
                prefix-list PL-FABRIC;
            }
            then reject;
        }
        term LU {
            from rib inet.3;
            then reject;
        }
        term CT {
            from rib bgp.transport.3;
            then reject;
        }
        term ACCEPT {
            then accept;
        }
    }
}
