/*
 * Topic:   BGP policy PS-IBGP-CR-EXPORT (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   cr1_ptx10001-36mr cr2_ptx10001-36mr
 *
 * Highlights:
 *  - As-deployed PS-IBGP-CR-EXPORT routing policy.
 *
 * Pair with:
 *  - evo/policy/communities.conf
 *  - evo/policy/community-loopback.conf
 *  - evo/policy/pl-metro-ring.conf
 *
 * Variables: none
 */
policy-options {
    policy-statement PS-IBGP-CR-EXPORT {
        term LOOPBACK {
            from {
                protocol direct;
                interface lo0.0;
            }
            then {
                community add CM-LOOPBACK;
                next-hop self;
                accept;
            }
        }
        term METRO-RING {
            from {
                community CM-SERVICE-EDGE;
                prefix-list PL-METRO-RING;
            }
            then {
                inactive: next-hop self;
                accept;
            }
        }
        term METRO-FABRIC {
            from community CM-ACCESS-FABRIC;
            then accept;
        }
    }
}
