/*
 * Topic:   BGP policy PS-METRO-FABRIC-IMPORT (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   cr1_ptx10001-36mr cr2_ptx10001-36mr
 *
 * Highlights:
 *  - As-deployed PS-METRO-FABRIC-IMPORT routing policy.
 *
 * Pair with:
 *  - evo/policy/communities.conf
 *
 * Variables: none
 */
policy-options {
    policy-statement PS-METRO-FABRIC-IMPORT {
        term ACCESS-FABRIC {
            from community CM-ACCESS-FABRIC;
            then accept;
        }
        term REJECT {
            then reject;
        }
    }
}
