/*
 * Topic:
 *   Service instance: evpn elan type5 (MEF E-LAN / EVP-LAN)
 *
 * Seen on:
 *   Evo: AN3 (ACX7100-48L)
 *
 * Highlights:
 *   - instance-type mac-vrf
 *   - EVPN Type-5 IP-prefix routes (L3 over EVPN)
 *   - MPLS encapsulation (SR-MPLS or LDP underlay)
 *   - no-control-word (matches remote PE)
 *   - RT-driven import/export
 *
 * Pair with (same-device dependencies):
 *   - evo/cos/classifiers.conf
 *   - evo/cos/cos-binding-ieee8021p.conf
 *   - evo/cos/rewrite-rules.conf
 *   - evo/firewall/filter-eswitch-color-blind.conf
 *   - evo/interfaces/physical-mtu.conf
 *   - evo/interfaces/vlan-bridge.conf
 *
 * JVD service mapping:
 *   METRO_L3VPN_4075 (elan_evp-lan_evpn-elan_type-5.conf):
 *     PEs (Evo): AN3 (ACX7100-48L), MEG1 (ACX7100-32C), MEG2 (ACX7509)
 *     PEs (Junos): MSE1 (MX304)
 *   evpn_group_60_4075 (elan_evp-lan_evpn-elan_type-5.conf):
 *     PEs (Evo): AN3 (ACX7100-48L), MEG1 (ACX7100-32C), MEG2 (ACX7509)
 *     PEs (Junos): MSE1 (MX304)
 *
 * Variables:
 *   $AC_INTF        e.g. et-0/0/13
 *   $INSTANCE_NAME  e.g. evpn_group_60_4075
 *   $IRB_UNIT       e.g. 4075
 *   $RD_1           e.g. 10.0.0.2:14075
 *   $RD_2           e.g. 63000:13075
 *   $ROUTER_ID      e.g. 10.0.0.2
 *   $UNIT           e.g. 4075
 *   $VLAN           e.g. 4075
 *   $VRF_TARGET     e.g. 61535:14075
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type mac-vrf;
        protocols {
            evpn {
                encapsulation mpls;
                default-gateway do-not-advertise;
                normalization;
                no-control-word;
            }
        }
        service-type vlan-based;
        route-distinguisher $RD_1;
        vrf-target target:$VRF_TARGET;
        vlans {
            V4000 {
                vlan-id $VLAN;
                interface $AC_INTF.$UNIT;
                l3-interface irb.$IRB_UNIT;
            }
        }
    }
    METRO_L3VPN_4075 {
        instance-type vrf;
        routing-options {
            router-id $ROUTER_ID;
        }
        protocols {
            evpn {
                ip-prefix-routes {
                    advertise direct-nexthop;
                    encapsulation mpls;
                }
            }
        }
        interface irb.$IRB_UNIT;
        route-distinguisher $RD_2;
        vrf-import PS-METRO_L3VPN_4075-IMPORT;
        vrf-export PS-METRO_L3VPN_4075-EXPORT;
        vrf-table-label;
    }
}
