/*
 * Topic:   Service instance: evpn elan bundle port based (MEF E-LAN / EP-LAN)
 *
 * Seen on:
 *   Evo: MA1.2 (ACX7024)
 *
 * Highlights:
 *   - instance-type mac-vrf
 *   - no-control-word (matches remote PE)
 *   - RT-driven import/export
 *
 * Pair with (same-device dependencies):
 *   - evo/cos/classifiers.conf
 *   - evo/cos/cos-binding-ieee8021p.conf
 *   - evo/cos/rewrite-rules.conf
 *   - evo/firewall/filter-eswitch-color-blind-l2cp.conf
 *   - evo/interfaces/ethernet-bridge.conf
 *   - evo/services/evpn-elan-bundle-port-based.conf
 *
 * JVD service mapping:
 *   MEF_EVPN_ELAN_PORT_BASED (elan_ep-lan_evpn_elan.conf):
 *     PEs (Evo): AN3 (ACX7100-48L), MA1.2 (ACX7024)
 *     PEs (Junos): MA5 (MX204)
 *
 * Variables:
 *   $AC_INTF        e.g. et-0/0/13
 *   $INSTANCE_NAME  e.g. MEF_EVPN_ELAN_PORT_BASED
 *   $RD             e.g. 10.0.0.18:4014
 *   $UNIT           e.g. 0
 *   $VRF_TARGET     e.g. 63535:4014
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type mac-vrf;
        protocols {
            evpn {
                no-control-word;
            }
        }
        service-type vlan-bundle;
        route-distinguisher $RD;
        vrf-target target:$VRF_TARGET;
        vlans {
            v-2 {
                interface $AC_INTF.$UNIT;
            }
        }
    }
}
