/*
 * Topic:   Service instance: l2circuit hot standby primary (MEF E-Line / EVPL)
 *
 * Seen on:
 *   Evo: AN3 (ACX7100-48L)
 *
 * Highlights:
 *   - Static targeted-LDP L2-circuit pseudowire (no routing-instance required)
 *
 * Pair with (same-device dependencies):
 *   - evo/cos/classifiers.conf
 *   - evo/cos/cos-binding-ieee8021p.conf
 *   - evo/cos/rewrite-rules.conf
 *   - evo/firewall/filter-ccc-color-blind.conf
 *   - evo/interfaces/physical-mtu.conf
 *   - evo/interfaces/vlan-ccc-vlan-map.conf
 *
 * JVD service mapping:
 *   l2ckt-vc2006 (eline_evpl_l2ckt_hsb.conf):
 *     PEs (Evo): AN3 (ACX7100-48L), MEG1 (ACX7100-32C)
 *   l2ckt-vc3333 (eline_evpl_l2ckt_hsb.conf):
 *     PEs (Evo): AN3 (ACX7100-48L), MEG2 (ACX7509)
 *
 * Variables:
 *   $AC_INTF  e.g. et-0/0/13
 *   $UNIT     e.g. 4006
 *   $VC_ID_1  e.g. 2006
 *   $VC_ID_2  e.g. 3333
 */
protocols {
    l2circuit {
        neighbor 10.0.0.6 {
            interface $AC_INTF.$UNIT {
                virtual-circuit-id $VC_ID_1;
                control-word;
                flow-label-transmit;
                flow-label-receive;
                encapsulation-type ethernet-vlan;
                ignore-mtu-mismatch;
                pseudowire-status-tlv;
                backup-neighbor 10.0.0.7 {
                    virtual-circuit-id $VC_ID_2;
                    hot-standby;
                }
            }
        }
    }
}
