/*
 * Topic: Policy accepting OSPF routes
 * Seen on:
 *   Junos: wanedge1_mx304 wanedge2_mx10008
 *   EVO: (none)
 * Count:
 *   wanedge1_mx304 1
 *   wanedge2_mx10008 1
 *   total 2
 * Pair with: none
 * Peers with: n/a
 * Variables: none
 */
policy-options {
    policy-statement send-ospf {
        term 2 {
            from protocol ospf;
            then accept;
        }
    }
}
