/*
 * Topic: Policy send-static accepting static routes
 * Seen on:
 *   Junos: wanedge2_mx10008
 *   EVO: (none)
 * Count:
 *   wanedge2_mx10008 1
 *   total 1
 * Pair with: none
 * Peers with: n/a
 * Variables: none
 */
policy-options {
    policy-statement send-static {
        term 1 {
            from protocol static;
            then accept;
        }
    }
}
