/*
 * Topic:   Service instance: evpn etree vlan based (MEF E-Tree / EVP-Tree)
 *
 * Seen on:
 *   Junos: MSE1 (MX304), MSE2 (MX304), MA4 (MX204), MA5 (MX204)
 *
 * Highlights:
 *   - instance-type evpn
 *   - EVPN E-Tree (root/leaf segregation)
 *   - RT-driven import/export
 *
 * Pair with (same-device dependencies):
 *   - junos/cos/classifiers.conf
 *   - junos/cos/cos-binding-ieee8021p.conf
 *   - junos/cos/cos-binding-mpls.conf
 *   - junos/cos/rewrite-rules.conf
 *   - junos/firewall/filter-bridge-color-aware.conf
 *   - junos/interfaces/vlan-bridge-esi-etree-root.conf
 *   - junos/interfaces/vlan-bridge-etree-leaf.conf
 *
 * JVD service mapping:
 *   evpn_group_80_4080 (etree_evp-tree_evpn-etree.conf):
 *     A-A Multihoming: MSE1 (MX304), MSE2 (MX304)
 *     PEs (Junos): MA4 (MX204), MA5 (MX204)
 *
 * Variables:
 *   $AC_INTF        e.g. ae10
 *   $INSTANCE_NAME  e.g. evpn_group_80_4080
 *   $RD             e.g. 10.0.0.10:4080
 *   $UNIT           e.g. 4080
 *   $VLAN           e.g. 4080
 *   $VRF_TARGET     e.g. 63536:4080
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type evpn;
        protocols {
            evpn {
                interface $AC_INTF.$UNIT;
                evpn-etree;
            }
        }
        vlan-id $VLAN;
        interface $AC_INTF.$UNIT;
        route-distinguisher $RD;
        vrf-export $INSTANCE_NAME;
        vrf-target target:$VRF_TARGET;
    }
}
