/*
 * Topic:
 *   Service instance: evpn elan vlan based floating pw (MEF E-Line / EVPL)
 *
 * Seen on:
 *   Junos: MSE1 (MX304), MSE2 (MX304)
 *
 * Highlights:
 *   - instance-type evpn
 *   - RT-driven import/export
 *
 * Pair with (same-device dependencies):
 *   - junos/cos/classifiers.conf
 *   - junos/cos/cos-binding-ieee8021p.conf
 *   - junos/cos/cos-binding-mpls.conf
 *   - junos/cos/rewrite-rules.conf
 *   - junos/interfaces/pseudowire-subscriber.conf
 *   - junos/interfaces/vlan-bridge-esi.conf
 *   - junos/services/l2circuit-floating-pw.conf
 *
 * JVD service mapping:
 *   l2circuit (eline_evpl_floating_pw.conf):
 *     PEs (Junos): MSE1 (MX304), MSE2 (MX304)
 *   l2ckt-vc10120 (eline_evpl_floating_pw.conf):
 *     PEs (Evo): MA1.2 (ACX7024)
 *     PEs (Junos): MSE1 (MX304), MSE2 (MX304)
 *
 * Variables:
 *   $AC_INTF        e.g. ae10
 *   $INSTANCE_NAME  e.g. 4004-evpn-floating-pw
 *   $RD             e.g. 10.0.0.10:40004
 *   $UNIT           e.g. 4004
 *   $VLAN           e.g. 4004
 *   $VRF_TARGET     e.g. 4004:4004
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type evpn;
        protocols {
            evpn;
        }
        vlan-id $VLAN;
        interface $AC_INTF.$UNIT;
        interface ps22.4004;
        route-distinguisher $RD;
        vrf-target target:$VRF_TARGET;
    }
}
