/*
 * Topic:
 *   Service instance: evpn vpws vlan based (MEF E-Line / EVPL)
 *
 * Seen on:
 *   Junos: AN1 (MX204), AN2 (ACX5448), AN4 (ACX710)
 *
 * Highlights:
 *   - instance-type evpn-vpws
 *   - EVPN-VPWS attachment-circuit with local/remote service-id
 *   - RT-driven import/export
 *
 * Pair with (same-device dependencies):
 *   - junos/cos/classifiers.conf
 *   - junos/cos/cos-binding-ieee8021p.conf
 *   - junos/cos/rewrite-rules.conf
 *   - junos/firewall/filter-ccc-color-blind.conf
 *   - junos/interfaces/vlan-ccc-vlan-map-esi.conf
 *   - junos/interfaces/vlan-ccc-vlan-map.conf
 *
 * JVD service mapping:
 *   evpn_group_30_4009 (eline_evpl_evpn_vpws_mh_e2e.conf):
 *     A-A Multihoming: AN1 (MX204), AN2 (ACX5448), AN3 (ACX7100-48L)
 *     A-A Multihoming: MA1.1 (ACX7024), MA1.2 (ACX7024)
 *   evpn_group_20_4010 (eline_evpl_evpn_vpws_sh_fabric.conf):
 *     PEs (Evo): AN3 (ACX7100-48L)
 *     PEs (Junos): AN4 (ACX710)
 *
 * Variables:
 *   $AC_INTF        e.g. ae11
 *   $INSTANCE_NAME  e.g. evpn_group_30_4009
 *   $LOCAL_VID      e.g. 1
 *   $RD             e.g. 10.0.0.0:4999
 *   $REMOTE_VID     e.g. 2
 *   $UNIT           e.g. 4009
 *   $VRF_TARGET     e.g. 63535:4999
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type evpn-vpws;
        protocols {
            evpn {
                interface $AC_INTF.$UNIT {
                    vpws-service-id {
                        local $LOCAL_VID;
                        remote $REMOTE_VID;
                    }
                }
            }
        }
        interface $AC_INTF.$UNIT;
        route-distinguisher $RD;
        vrf-target target:$VRF_TARGET;
    }
}
