/*
 * Topic:
 *   Service instance: evpn elan type5 (MEF E-LAN / EVP-LAN)
 *
 * Seen on:
 *   Junos: MSE1 (MX304)
 *
 * Highlights:
 *   - instance-type virtual-switch
 *   - EVPN Type-5 IP-prefix routes (L3 over EVPN)
 *   - MPLS encapsulation (SR-MPLS or LDP underlay)
 *   - no-control-word (matches remote PE)
 *   - RT-driven import/export
 *   - Local-switched (LSW) bridge-domain — no MPLS, used in E-Access hand-off scenarios
 *
 * Pair with (same-device dependencies):
 *   - junos/cos/classifiers.conf
 *   - junos/cos/cos-binding-ieee8021p.conf
 *   - junos/cos/rewrite-rules.conf
 *
 * JVD service mapping:
 *   METRO_L3VPN_4075 (elan_evp-lan_evpn-elan_type-5.conf):
 *     PEs (Evo): AN3 (ACX7100-48L), MEG1 (ACX7100-32C), MEG2 (ACX7509)
 *     PEs (Junos): MSE1 (MX304)
 *   evpn_group_60_4075 (elan_evp-lan_evpn-elan_type-5.conf):
 *     PEs (Evo): AN3 (ACX7100-48L), MEG1 (ACX7100-32C), MEG2 (ACX7509)
 *     PEs (Junos): MSE1 (MX304)
 *
 * Variables:
 *   $AC_INTF        e.g. xe-0/0/13:2
 *   $INSTANCE_NAME  e.g. evpn_group_60_4075
 *   $IRB_UNIT       e.g. 4075
 *   $RD_1           e.g. 10.0.0.10:14075
 *   $RD_2           e.g. 63200:13075
 *   $ROUTER_ID      e.g. 10.0.0.10
 *   $UNIT           e.g. 4075
 *   $VLAN           e.g. 4075
 *   $VRF_TARGET     e.g. 61535:14075
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type virtual-switch;
        protocols {
            evpn {
                encapsulation mpls;
                default-gateway do-not-advertise;
                extended-vlan-list 4075;
                no-control-word;
            }
        }
        bridge-domains {
            BD_evpn_group_60_4075 {
                vlan-id $VLAN;
                interface $AC_INTF.$UNIT;
                routing-interface irb.$IRB_UNIT;
            }
        }
        route-distinguisher $RD_1;
        vrf-target target:$VRF_TARGET;
    }
    METRO_L3VPN_4075 {
        instance-type vrf;
        routing-options {
            router-id $ROUTER_ID;
            auto-export;
        }
        protocols {
            evpn {
                ip-prefix-routes {
                    advertise direct-nexthop;
                    encapsulation mpls;
                }
            }
        }
        interface irb.$IRB_UNIT;
        route-distinguisher $RD_2;
        vrf-import PS-METRO_L3VPN_4075-IMPORT;
        vrf-export PS-METRO_L3VPN_4075-EXPORT;
        vrf-table-label;
    }
}
