/*
 * Topic: LLDP enabled on all interfaces
 * Seen on:
 *   Junos: (none)
 *   EVO: agn2_acx7100-32c cr1_ptx10004
 * Count:
 *   agn2_acx7100-32c 1
 *   cr1_ptx10004 1
 *   total 2
 * Pair with: none
 *
 * Variables: none
 */
protocols {
    lldp {
        interface all;
    }
}
