/*
 * Topic:   IPv6 router access filter
 * Seen on:
 *   Junos: (none)
 *   EVO:   ag1-1_acx7100-32c
 * Count:
 *   ag1-1_acx7100-32c 1
 *   total 1
 * Pair with: none
 *
 * Peers with: n/a
 * Variables: none
 */
firewall {
  family inet6 {
    filter IPV6-ROUTER-ACCESS {
      interface-specific;
      term ALL-ELSE {
        then {
          count LAST;
          accept;
        }
      }
    }
  }
}
