/*
 * Topic:   policy-statement PS-LOCAL-LOOPBACK
 * Seen on:
 *   Junos: mse1_mx304 mse2_mx304
 *   EVO:   (none)
 * Pair with:
 *  - junos/policy-options/community/cm-loopback.conf
 * Variables: none
 */
policy-options {
    policy-statement PS-LOCAL-LOOPBACK {
        term LOCAL-LOOPBACK {
            from {
                protocol direct;
                interface lo0.0;
                route-filter 1.1.0.0/16 prefix-length-range /32-/32;
                route-filter 1.1.10.10/32 exact;
            }
            then {
                community add CM-LOOPBACK;
                accept;
            }
        }
        term REJECT {
            then reject;
        }
    }
}
