/*
 * Topic:   BGP policy PS-MSE-IMPORT (Junos)
 * Seen on:
 *   Junos: mse1_mx304 mse2_mx304
 *   EVO:   (none)
 *
 * Highlights:
 *  - As-deployed PS-MSE-IMPORT routing policy.
 *
 * Pair with: none
 *
 * Variables: none
 */
policy-options {
    policy-statement PS-MSE-IMPORT {
        term SET-LP {
            then {
                local-preference 90;
                accept;
            }
        }
    }
}
