/*
 * Topic: OSPF area 0 with protected core links and two access units
 * Seen on:
 *   Junos: (none)
 *   EVO: wanedge4_acx7100-48l
 * Count:
 *   wanedge4_acx7100-48l 1
 *   total 1
 * Pair with: none
 * Variables: none
 */
protocols {
    ospf {
        area 0.0.0.0 {
            interface et-0/0/49.0 {
                node-link-protection;
                bfd-liveness-detection {
                    minimum-interval 10;
                    multiplier 3;
                    full-neighbors-only;
                }
                ldp-synchronization;
            }
            interface lo0.0 {
                passive;
            }
            interface ae4.0 {
                node-link-protection;
                bfd-liveness-detection {
                    minimum-interval 10;
                    multiplier 3;
                    full-neighbors-only;
                }
                ldp-synchronization;
            }
            interface et-0/0/50.0 {
                bfd-liveness-detection {
                    minimum-interval 10;
                    multiplier 3;
                    full-neighbors-only;
                }
                ldp-synchronization;
            }
            interface et-0/0/1.514;
            interface et-0/0/0.1001;
        }
    }
}
