/*
 * Topic: Ordered global two-group application
 * Seen on:
 *   Junos: ma4_mx204
 *   EVO: (none)
 * Count:
 *   ma4_mx204 1
 *   total 1
 * Pair with: none
 *
 * Variables:
 *   $GROUP_A   e.g. etree_evpn_group_80
 *   $GROUP_B   e.g. l3vpn_ospf_serv_map
 */
apply-groups [ $GROUP_A $GROUP_B ];