/*
 * Topic: Enhanced-IP network services mode
 * Seen on:
 *   Junos: ap1_mx304 ap2_mx10004 wanedge1_mx304 wanedge2_mx10004
 *   EVO: (none)
 * Count:
 *   ap1_mx304 1
 *   ap2_mx10004 1
 *   wanedge1_mx304 1
 *   wanedge2_mx10004 1
 *   total 4
 * Highlights:
 *  - Sets the chassis network-services mode to enhanced IP.
 * Pair with: none
 * Peers with: n/a
 * Variables: none
 */
chassis {
    network-services enhanced-ip;
}
