/*
 * Topic:   esis
 * Seen on:
 *   Junos: an1_mx204
 *   EVO:   meg1_acx7100-32c
 * Count:
 *   an1_mx204 1
 *   meg1_acx7100-32c 1
 *   total 2
 * Pair with: none
 * Variables: none
 */
protocols {
    esis {
        disable;
    }
}
