/*
 * Topic:   IS-IS logical interface
 * Seen on:
 *   Junos: mdr2_mx10003
 *   EVO:   ma3_acx7100-48l mdr1_acx7509
 * Count:
 *   ma3_acx7100-48l 2
 *   mdr1_acx7509 2
 *   mdr2_mx10003 2
 *   total 6
 * Peers with: n/a
 * Variables:
 *   $ISIS_INSTANCE   e.g. metro-a
 */
protocols {
  isis-instance $ISIS_INSTANCE {
    interface lo0.0 {
      passive;
    }
  }
}
