/*
 * Topic:   ISIS core interface
 * Seen on:
 *   Junos: (none)
 *   EVO:   mdr1_acx7509 meg2_acx7509
 * Pair with:
 *  - evo/interfaces/ifl-core-inet-iso-inet6-mpls.conf
 * Variables:
 *   $CORE_INTF   e.g. et-1/0/4.0
 */
protocols {
    isis {
        interface $CORE_INTF {
            level 2 {
                post-convergence-lfa {
                    node-protection cost 16777214;
                }
                application-specific {
                    attribute-group ASLA {
                        advertise-delay-metric;
                        te-metric 10;
                        admin-group [ blue green ];
                        application {
                            flex-algorithm;
                        }
                    }
                }
            }
            level 1 disable;
            delay-metric 10;
            point-to-point;
            family inet {
                bfd-liveness-detection {
                    minimum-interval 100;
                    multiplier 3;
                    no-adaptation;
                }
            }
        }
    }
}
