/*
 * Topic:   ISIS source-packet-routing
 * Seen on:
 *   Junos: (none)
 *   EVO:   ma3_acx7100-48l
 * Pair with:
 *  - evo/groups/gr-isis-bcp.conf
 * Variables: none
 */
protocols {
    isis {
        apply-groups GR-ISIS-BCP;
        source-packet-routing;
    }
}
