/*
 * Topic:   IS-IS logical interface
 * Seen on:
 *   Junos: an1_mx204 an2_acx5448 an4_acx710
 *   EVO:   ag1-1_acx7100-32c ag1-2_acx7100-32c
 * Variables:
 *   $ADMIN_GROUP_1   e.g. green
 *   $ADMIN_GROUP_2   e.g. blue
 *   $CORE_INTF   e.g. ae71.0
 *   $DELAY_METRIC   e.g. 105
 *   $TE_METRIC   e.g. 110
 */
protocols {
  isis {
    interface $CORE_INTF {
      level 1 {
        post-convergence-lfa {
          node-protection cost 16777214;
        }
        application-specific {
          attribute-group ASLA {
            advertise-delay-metric;
            te-metric $TE_METRIC;
            admin-group [ $ADMIN_GROUP_1 $ADMIN_GROUP_2 ];
            application {
              flex-algorithm;
            }
          }
        }
      }
      delay-metric $DELAY_METRIC;
      point-to-point;
      family inet {
        bfd-liveness-detection {
          minimum-interval 100;
          multiplier 3;
          no-adaptation;
        }
      }
    }
  }
}
