/*
 * Topic: Static-label Ethernet VLAN pseudowire with transport community
 * Seen on:
 *   Junos: (none)
 *   EVO: ma1-2_acx7024
 * Count:
 *   ma1-2_acx7024 10
 *   total 10
 * Pair with: none
 *
 * Variables:
 *   $REMOTE_PE_V4     e.g. 1.1.10.10
 *   $AC_INTF          e.g. et-0/0/14.301
 *   $LABEL_IN         e.g. 1000001
 *   $LABEL_OUT        e.g. 1000001
 *   $VC_ID            e.g. 1001
 *   $COLOR_COMMUNITY  e.g. CM-TC-MAP2GOLD
 */
protocols {
    l2circuit {
        neighbor $REMOTE_PE_V4 {
            interface $AC_INTF {
                static {
                    incoming-label $LABEL_IN;
                    outgoing-label $LABEL_OUT;
                }
                virtual-circuit-id $VC_ID;
                community $COLOR_COMMUNITY;
                encapsulation-type ethernet-vlan;
            }
        }
    }
}