/*
 * Topic:   MPLS controller and segment-routing settings
 * Seen on:
 *   Junos: (none)
 *   EVO:   cr2_ptx10001-36mr
 * Pair with:
 *  - evo/protocols/pcep-pccd.conf
 * Variables: none
 */
protocols {
  mpls {
    lsp-external-controller pccd;
    admin-groups {
      blue 1;
      green 2;
      red 3;
    }
    no-propagate-ttl;
    icmp-tunneling;
    label-range {
      srgb-label-range 16000 24000;
    }
    ipv6-tunneling;
  }
}
