/*
 * Topic: Scheduler map for the four-class model
 * Seen on:
 *   Junos: (none)
 *   EVO: p1_ptx10003-80c p2_ptx10001-36mr
 * Count:
 *   p1_ptx10003-80c 1
 *   p2_ptx10001-36mr 1
 *   total 2
 * Highlights:
 *  - Binds BEST-EFFORT, FC-HIGH, FC-LLQ and CONTROL to schedulers s0-s3.
 * Pair with:
 *  - evo/class-of-service/forwarding-classes/fc-4queue-model.conf
 *  - evo/class-of-service/schedulers/sc-4class-priority.conf
 *
 * Peers with: n/a
 * Variables: none
 */
class-of-service {
    scheduler-maps {
        sched-map {
            forwarding-class BEST-EFFORT scheduler s0;
            forwarding-class FC-HIGH scheduler s1;
            forwarding-class FC-LLQ scheduler s2;
            forwarding-class CONTROL scheduler s3;
        }
    }
}
