/*
 * Topic: Forwarding table with per-packet load balancing
 * Seen on:
 *   Junos: (none)
 *   EVO: agn1_acx7100-32c agn2_acx7100-32c cr1_ptx10004
 * Count:
 *   agn1_acx7100-32c 1
 *   agn2_acx7100-32c 1
 *   cr1_ptx10004 1
 *   total 3
 * Highlights:
 *  - Exports `PS-PPLB` to the forwarding table, so equal-cost routes install as multiple forwarding next hops.
 * Pair with:
 *  - evo/policy-options/policy-statement/ps-pplb.conf
 *
 * Peers with: n/a
 * Variables: none
 */
routing-options {
    forwarding-table {
        export PS-PPLB;
    }
}
