/*
 * Topic:
 *   Class-of-service: cos binding mpls (MEF E-Access, E-LAN / EP-LAN, E-LAN / EVP-LAN, E-Line / EPL, E-Line / EVPL, E-Tree / EVP-Tree)
 *
 * Seen on:
 *   Junos: MA5 (MX204), MSE1 (MX304), AN1 (MX204), AN2 (ACX5448), AN4 (ACX710), MSE2 (MX304), MA4 (MX204)
 *
 * Highlights:
 *   - MPLS core-facing CoS binding (classify + rewrite EXP)
 *
 * Pair with (same-device dependencies):
 *   - junos/cos/classifiers.conf
 *   - junos/cos/forwarding-classes.conf
 *   - junos/cos/rewrite-rules.conf
 *   - junos/cos/scheduler-map.conf
 *   - junos/cos/schedulers.conf
 *
 * Variables:
 *   (none)
 */
interfaces {
    $AC_INTF {
        scheduler-map SM-5G-SCHEDULER;
        unit $UNIT {
            classifiers {
                exp CL-MPLS;
            }
            rewrite-rules {
                exp RR-MPLS;
            }
        }
    }
}

