/*
 * Topic:   Class-of-service: schedulers (MEF E-Access, E-LAN / EP-LAN, E-LAN / EVP-LAN, E-Line / EPL, E-Line / EVPL, E-Tree / EVP-Tree)
 *
 * Seen on:
 *   Junos: MA5 (MX204), MSE1 (MX304), MSE2 (MX304), MA4 (MX204)
 *
 * Highlights:
 *   - Per-queue scheduler shaping / buffer / priority
 *
 * Pair with (same-device dependencies):
 *   (none derived)
 *
 * Variables:
 *   (none)
 */
schedulers {
    SC-SIGNALING {
        transmit-rate percent 5;
        buffer-size percent 5;
        priority high;
    }
    SC-LLQ {
        shaping-rate percent 40;
        buffer-size percent 10;
        priority strict-high;
    }
    SC-REALTIME {
        transmit-rate percent 15;
        buffer-size percent 20;
        priority medium-high;
    }
    SC-HIGH {
        transmit-rate percent 10;
        buffer-size percent 20;
        priority high;
    }
    SC-CONTROL {
        transmit-rate percent 5;
        buffer-size percent 5;
        priority high;
    }
    SC-MEDIUM {
        transmit-rate percent 10;
        buffer-size percent 10;
        priority low;
    }
    SC-LOW {
        transmit-rate percent 10;
        buffer-size percent 10;
        priority low;
    }
    SC-BEST-EFFORT {
        transmit-rate {
            remainder;
        }
        buffer-size {
            remainder;
        }
        priority low;
    }
}
