/*
 * Topic: Forwarding-table export of two load-balance policies
 * Seen on:
 *   Junos: wanedge2_mx10008
 *   EVO: (none)
 * Count:
 *   wanedge2_mx10008 1
 *   total 1
 * Pair with:
 *  - junos/policy-options/policy-statement/ps-pplb-accept.conf
 *
 * Peers with: n/a
 * Variables: none
 */
routing-options {
    forwarding-table {
        export [ load_balance pplb ];
    }
}
