/*
 * Topic: Router ID
 * Seen on:
 *   Junos: wanedge1_mx304 wanedge2_mx10008
 *   EVO: (none)
 * Count:
 *   wanedge1_mx304 1
 *   wanedge2_mx10008 1
 *   total 2
 * Pair with: none
 * Peers with: n/a
 * Variables (example values from wanedge1_mx304):
 *   $ROUTER_ID  e.g. 10.10.0.12
 */
routing-options {
    router-id $ROUTER_ID;
}
