/*
 * Topic:   Interface: vlan ccc qinq stacked qinq tpid (MEF E-Access)
 *
 * Seen on:
 *   Evo: MA3 (ACX7100-48L)
 *
 * Highlights:
 *   - encapsulation vlan-ccc
 *
 * Pair with (same-device dependencies):
 *   - evo/cos/classifiers.conf
 *   - evo/cos/cos-binding-ieee8021p.conf
 *   - evo/cos/cos-binding-mpls.conf
 *   - evo/cos/rewrite-rules.conf
 *   - evo/services/evpn-vpws-lsw.conf
 *   - evo/services/l2circuit-lsw.conf
 *
 * Variables:
 *   $AC_INTF         e.g. et-0/0/51
 *   $MTU             e.g. 9102
 *   $OUTER_VID_TPID  e.g. 0x88a8.4082
 *   $UNIT            e.g. 4082
 */
$AC_INTF {
    mtu $MTU;
    ether-options {
        ethernet-switch-profile {
            tag-protocol-id [ 0x8100 0x88a8 ];
        }
    }
    unit $UNIT {
        encapsulation vlan-ccc;
        vlan-tags outer $OUTER_VID_TPID;
    }
}
