/*
 * Topic:   Interface: vlan ccc vlan map esi 2 units (MEF E-Line / EVPL)
 *
 * Seen on:
 *   Evo: MEG1 (ACX7100-32C), MEG2 (ACX7509), MA1.1 (ACX7024), MA1.2 (ACX7024)
 *
 * Highlights:
 *   - encapsulation vlan-ccc
 *   - ESI multihoming
 *
 * Pair with (same-device dependencies):
 *   - evo/cos/classifiers.conf
 *   - evo/cos/cos-binding-ieee8021p.conf
 *   - evo/cos/rewrite-rules.conf
 *   - evo/firewall/filter-ccc-color-blind.conf
 *   - evo/services/evpn-fxc-vlan-aware.conf
 *
 * Variables:
 *   $AC_INTF      e.g. ae67
 *   $ESI_ID_1     e.g. 00:10:44:11:50:12:02:00:00:00
 *   $ESI_ID_2     e.g. 00:10:44:11:50:12:01:00:00:00
 *   $INPUT_VID_1  e.g. 3400
 *   $INPUT_VID_2  e.g. 3000
 *   $UNIT_1       e.g. 4002
 *   $UNIT_2       e.g. 4001
 *   $VLAN_1       e.g. 4002
 *   $VLAN_2       e.g. 4001
 */
$AC_INTF {
    unit $UNIT_1 {
        encapsulation vlan-ccc;
        vlan-id $VLAN_1;
        input-vlan-map {
            push;
            vlan-id $INPUT_VID_1;
        }
        output-vlan-map pop;
        esi {
            $ESI_ID_1;
            all-active;
        }
        family ccc {
            filter {
                input f_vlan-based_fam_ccc;
            }
        }
    }
    unit $UNIT_2 {
        encapsulation vlan-ccc;
        vlan-id $VLAN_2;
        input-vlan-map {
            push;
            vlan-id $INPUT_VID_2;
        }
        output-vlan-map pop;
        esi {
            $ESI_ID_2;
            all-active;
        }
        family ccc {
            filter {
                input f_vlan-based_fam_ccc;
            }
        }
    }
}
