/*
 * Topic:   Interface: vlan bridge (MEF E-Line / EVPL)
 *
 * Seen on:
 *   Evo: MA1.2 (ACX7024)
 *
 * Highlights:
 *   - encapsulation flexible-ethernet-services
 *
 * Pair with (same-device dependencies):
 *   - evo/cos/classifiers.conf
 *   - evo/cos/cos-binding-ieee8021p.conf
 *   - evo/cos/rewrite-rules.conf
 *   - evo/firewall/filter-eswitch-color-blind.conf
 *   - evo/services/bgp-vpls-p2p.conf
 *
 * Variables:
 *   $AC_INTF  e.g. et-0/0/12
 *   $UNIT     e.g. 4005
 *   $VLAN     e.g. 4005
 */
$AC_INTF {
    vlan-tagging;
    encapsulation flexible-ethernet-services;
    unit $UNIT {
        encapsulation vlan-bridge;
        vlan-id $VLAN;
        family ethernet-switching {
            filter {
                input f_vlan_based_fam_bridge;
            }
        }
    }
}
