/*
 * Topic:   Interface: vlan bridge esi bundle (MEF E-LAN / EVP-LAN)
 *
 * Seen on:
 *   Evo: MEG1 (ACX7100-32C), MEG2 (ACX7509)
 *
 * Highlights:
 *   - encapsulation vlan-bridge
 *   - ESI multihoming
 *
 * Pair with (same-device dependencies):
 *   - evo/cos/classifiers.conf
 *   - evo/cos/cos-binding-ieee8021p.conf
 *   - evo/cos/rewrite-rules.conf
 *   - evo/firewall/filter-eswitch-color-blind.conf
 *   - evo/services/evpn-elan-vlan-bundle.conf
 *
 * Variables:
 *   $AC_INTF          e.g. ae67
 *   $ESI_ID           e.g. 00:81:10:13:10:10:10:00:00:01
 *   $UNIT             e.g. 4013
 *   $VLAN_LIST_END    e.g. 4014
 *   $VLAN_LIST_START  e.g. 4013
 */
$AC_INTF {
    unit $UNIT {
        encapsulation vlan-bridge;
        vlan-id-list $VLAN_LIST_START-$VLAN_LIST_END;
        esi {
            $ESI_ID;
            all-active;
        }
        family ethernet-switching {
            filter {
                input f_elan-evpn;
            }
        }
    }
}
