/*
 * Topic:   BGP community definitions — tier marker + default direct redistribution
 * Variant: Evolved-OS (EVO)
 * Seen on:
 *   Junos: (none)
 *   EVO:   leaf1_qfx5130-32cd leaf2_qfx5130-32cd leaf3_qfx5130-32cd leaf4_qfx5130-32cd spine1_qfx5220-32cd spine2_qfx5220-32cd
 *
 * Highlights:
 *  - FROM_SPINE_FABRIC_TIER (0:15) = CLOS loop-prevention marker stamped by
 *    spines and rejected by leafs (see clos-loop-prevention snip)
 *  - DEFAULT_DIRECT_V4 identifies locally-redistributed direct routes; the
 *    high-order tag encodes the tier — leafs use `5:20007`, spines use
 *    `1:20007` for the same community, the low-order `21001:26000` is the
 *    shared fabric selector
 *  - This frontend fabric is IPv4-only — there is no DEFAULT_DIRECT_V6 and
 *    no per-tenant community (contrast the multitenancy-backend JVD)
 *
 * Pair with:
 *  - evo/policy/clos-loop-prevention.conf  (consumer of FROM_SPINE_FABRIC_TIER)
 *  - evo/policy/allpodnetworks-direct-redistribution.conf  (consumer of DEFAULT_DIRECT_V4)
 *
 * Variables (example values from leaf3_qfx5130-32cd / spine1_qfx5220-32cd):
 *   $LOCAL_TIER_TAG   e.g. 5   (leaf) or 1 (spine)
 */
policy-options {
    community DEFAULT_DIRECT_V4 members [ ${LOCAL_TIER_TAG}:20007 21001:26000 ];
    community FROM_SPINE_FABRIC_TIER members 0:15;
}
