/*
 * Topic: L3VPN VRF with eBGP sessions to two customer routers
 * Seen on:
 *   Junos: ap1_mx304 ap2_mx10004
 *   EVO: (none)
 * Count:
 *   ap1_mx304 3
 *   ap2_mx10004 3
 *   total 6
 * Highlights:
 *  - Unicast order-entry VRF toward both customer routers; `vrf-table-label` allows an IP lookup on egress.
 * Pair with:
 *  - junos/interfaces/ifl-vlan-inet.conf
 *  - junos/policy-options/policy-statement/ps-accept-direct.conf
 *  - junos/protocols/bgp-ibgp-full-mesh-5.conf
 *
 * Variables (example values from ap1_mx304):
 *   $INSTANCE_NAME     e.g. VRF21
 *   $PE_LOCAL_V4_1     e.g. 10.101.48.41
 *   $BGP_EXPORT_POL    e.g. PS-ADV_DIRECT
 *   $CE_PEER_V4_1      e.g. 10.101.48.42
 *   $ASN_CUSTOMER_1    e.g. 64520
 *   $PE_LOCAL_V4_2     e.g. 10.101.49.41
 *   $CE_PEER_V4_2      e.g. 10.101.49.42
 *   $ASN_CUSTOMER_2    e.g. 64521
 *   $AC_IFL_A          e.g. et-0/0/6.21
 *   $AC_IFL_B          e.g. et-0/0/11.21
 *   $LOOPBACK_V4       e.g. 10.200.50.14
 *   $RD_SUB_ASSIGNED   e.g. 221
 *   $RT_AS             e.g. 64512
 *   $RT_ID             e.g. 21
 */
routing-instances {
    $INSTANCE_NAME {
        instance-type vrf;
        protocols {
            bgp {
                group TGN_AF_CR1 {
                    type external;
                    local-address $PE_LOCAL_V4_1;
                    export $BGP_EXPORT_POL;
                    neighbor $CE_PEER_V4_1 {
                        peer-as $ASN_CUSTOMER_1;
                    }
                }
                group TGN_AF_CR2 {
                    type external;
                    local-address $PE_LOCAL_V4_2;
                    export $BGP_EXPORT_POL;
                    neighbor $CE_PEER_V4_2 {
                        peer-as $ASN_CUSTOMER_2;
                    }
                }
            }
        }
        interface $AC_IFL_A;
        interface $AC_IFL_B;
        route-distinguisher $LOOPBACK_V4:$RD_SUB_ASSIGNED;
        vrf-target target:$RT_AS:$RT_ID;
        vrf-table-label;
    }
}
