/*
 * Topic: Enhanced-IP network services mode
 * Seen on:
 *   Junos: (none)
 *   EVO: cr1_acx7100-48l
 * Count:
 *   cr1_acx7100-48l 1
 *   total 1
 * Highlights:
 *  - Sets the chassis network-services mode to enhanced IP.
 * Pair with: none
 * Peers with: n/a
 * Variables: none
 */
chassis {
    network-services enhanced-ip;
}
