/*
 * Topic: Route-target community PS-Internet-COMM for Internet VRF routes
 * Seen on:
 *   Junos: (none)
 *   EVO: cr1_ptx10004
 * Count:
 *   cr1_ptx10004 1
 *   total 1
 * Pair with: none
 *
 * Peers with: n/a
 * Variables (example values from cr1_ptx10004):
 *   $RT_AS  e.g. 100
 *   $RT_ID  e.g. 1
 */
policy-options {
    community PS-Internet-COMM members target:$RT_AS:$RT_ID;
}
