/*
 * Topic:   SRv6 locator redistribution / summarization at AS boundary —
 *          policy + IS-IS export pattern that lets domain-internal
 *          locators be summarized into the inter-AS BGP table.
 * Seen on:
 *   Junos: br2_mx304 cr1_mx10004 cr2_mx2010
 *   EVO:   br1_ptx10002-36qdd
 *
 * Highlights:
 *  - At a Border Router, `protocols isis { export PS-SRV6-LOC-EXPORT; }`
 *    leaks the local domain's per-Flex-Algo locator prefixes into BGP
 *    so the far AS can resolve service nexthops via SRv6.
 *  - `policy-options policy-statement PS-SRV6-LOC-EXPORT` filters by
 *    locator block (matched on `from route-filter`) and applies a
 *    summary or per-locator advertisement depending on the inter-AS
 *    design (per the JVD's "strict vs cascade" transport-class
 *    resolution choice).
 *  - At a CR (intra-AS), the same pattern is used to redistribute
 *    summarized far-domain locators learned from the BR back into
 *    IS-IS so internal routers can resolve them with a single LSP entry.
 *
 * Pair with:
 *  - junos/transport/inter-as-option-c.conf        (eBGP carrying these)
 *  - junos/transport/isis-srv6-flex-algo.conf      (locator definitions)
 *  - junos/policy/srv6-redistribution.conf         (the policy bodies)
 *
 * Variables (example values):
 *   $SUMMARY_PREFIX_FA_0   e.g. 5f00:1::/24
 *   $SUMMARY_PREFIX_FA_128 e.g. 5f00:a1::/24
 *   $SUMMARY_PREFIX_FA_129 e.g. 5f00:b1::/24
 */
protocols {
    isis {
        export PS-SRV6-LOC-EXPORT;
    }
    bgp {
        group GR-IBGP-ASBR-SRV6 {
            export PS-SRV6-LOC-EXPORT;
        }
    }
}
policy-options {
    policy-statement PS-SRV6-LOC-EXPORT {
        term TR-SUM-FA-0 {
            from {
                route-filter $SUMMARY_PREFIX_FA_0 exact;
            }
            then accept;
        }
        term TR-SUM-FA-128 {
            from {
                route-filter $SUMMARY_PREFIX_FA_128 exact;
            }
            then accept;
        }
        term TR-SUM-FA-129 {
            from {
                route-filter $SUMMARY_PREFIX_FA_129 exact;
            }
            then accept;
        }
    }
}
