/*
 * Topic: UDP tunnel decapsulation
 * Seen on:
 *   Junos: (none)
 *   EVO: cr1_ptx10004
 * Count:
 *   cr1_ptx10004 1
 *   total 1
 * Highlights:
 *  - Enables UDP tunnel decapsulation in the forwarding plane.
 * Pair with: none
 *
 * Peers with: n/a
 * Variables: none
 */
forwarding-options {
    tunnels {
        udp;
    }
}
